
var webtrekkConfig = webtrekkConfig || {
    trackId: "778835614863159",
    trackDomain : "edidomus01.webtrekk.net",
	  domain : "www.cucchiaio.it",
	  cookie : "3",
	  contentId : "",
    tabBrowsing: false,
    execCDB: false,
    execRTA: false,
    safetag: {
        async: true,
        timeout: 2000,
        /** Load SafeTag from Webtrekk Server */
        safetagDomain: "responder.wt-safetag.com",
        safetagId: "778835614863159",
        /** Load SafeTag from Customer Server */
        // customDomain: "www.domain.de",
        // customPath: "javascripts/webtrekk_safetag.js",
        option: {}
    }
};

/**
 ************ Don't change anything beyond this line ************
 ********************* Start webtrekk_v4.js *********************
 */
var webtrekkUnloadObjects=webtrekkUnloadObjects||[],webtrekkLinktrackObjects=webtrekkLinktrackObjects||[],webtrekkHeatmapObjects=webtrekkHeatmapObjects||[],webtrekkV3=function(g){var y=function(a,c){"1"!=f.cookie||(f.optOut||f.deactivatePixel)||f.firstParty();var b=c?c:f.formObject&&"noForm"!=a?"form":"link";!1!=f.beforeUnloadPixel?f.beforeUnloadPixel():"form"==b&&f.executePlugin(f.getPluginConfig("form","before"));var e="";if(f.config.linkId&&(e+="&ct="+f.wtEscape(f.maxlen(f.wtUnescape(f.config.linkId),
255)))){f.linktrackOut&&(e+="&ctx=1");var d=f.ccParams;"string"==typeof d&&""!=d&&(e+=d)}if(f.wtEp)if(f.wtEpEncoded)e+=f.wtEp;else if(d=f.wtEp,"string"==typeof d&&""!=d)for(var d=d.split(/;/),l=0;l<d.length;l++)if(f.wtTypeof(d[l])){var k=d[l].split(/=/);f.checkSC("custom")&&(k[1]=f.decrypt(k[1]));k[1]=f.wtEscape(k[1]);e+="&"+k[0]+"="+k[1]}"noForm"!=a&&(e+=f.checkFormTracking());""!=e&&(f.quicksend(f.wtEscape(f.contentId.split(";")[0])+",1,"+f.baseparams(),e),f.config.linkId="",f.ccParams="",f.wtEp=
"");!1!=f.afterUnloadPixel?f.afterUnloadPixel():"form"==b&&f.executePlugin(f.getPluginConfig("form","after"))},s=function(a){var c,b,e=document.getElementById(f.heatmapRefpoint);b=e&&null!==e?c=0:c=-1;if(e&&null!==e&&f.wtTypeof(e.offsetLeft))for(;e;)c+=0<=e.offsetLeft?e.offsetLeft:0,b+=0<=e.offsetTop?e.offsetTop:0,e=e.offsetParent;var d=e=0;a||(a=window.event);if(a.pageX||a.pageY)e=a.pageX,d=a.pageY;else if(a.clientX||a.clientY)if(e=a.clientX,d=a.clientY,f.isIE)if(0<document.body.scrollLeft||0<document.body.scrollTop)e+=
document.body.scrollLeft,d+=document.body.scrollTop;else if(0<document.documentElement.scrollLeft||0<document.documentElement.scrollTop)e+=document.documentElement.scrollLeft,d+=document.documentElement.scrollTop;a=0;a=f.isIE?document.body.clientWidth:self.innerWidth-16;var l=!0;if(e>=a||!f.sentFullPixel)l=!1;(0<=b||0<=c)&&(e>c&&d>b)&&(e="-"+(e-c),d="-"+(d-b));l&&"1"==f.heatmap&&(f.executePlugin(f.getPluginConfig("heatmap","before")),f.quicksend(f.wtEscape(f.contentId.split(";")[0])+","+e+","+d,"",
"hm"+(f.fileSuffix?".pl":"")),f.executePlugin(f.getPluginConfig("heatmap","after")))},u=function(){"undefined"!==typeof wt_heatmap?window.setTimeout(function(){wt_heatmap()},1E3):("undefined"===typeof wt_heatmap_retry&&(window.wt_heatmap_retry=0),wt_heatmap_retry++,60>wt_heatmap_retry&&window.setTimeout(function(){u()},1E3))},m=function(){"undefined"!==typeof wt_overlay?window.setTimeout(function(){wt_overlay()},1E3):("undefined"===typeof wt_overlay_retry&&(window.wt_overlay_retry=0),wt_overlay_retry++,
60>wt_overlay_retry&&window.setTimeout(function(){m()},1E3))},x=function(a,c){var b=f.urlParam(location.href,a,!1),e=f.urlParam(location.href,"wt_t",!1),d=(new Date).getTime(),l=RegExp(c),e=e?parseInt(e)+9E5:d-9E5;return b&&l.test(b)&&e>d?b:!1},h=webtrekkConfig,f=this;g||(g=h);this.defaultAttribute="contentId linkId trackId trackDomain domain linkTrack linkTrackParams linkTrackPattern linkTrackReplace linkTrackDownloads linkTrackIgnorePattern customParameter crmCategory urmCategory customClickParameter customSessionParameter customTimeParameter customCampaignParameter customEcommerceParameter orderValue currency orderId product productCost productQuantity productCategory productStatus couponValue customerId contentGroup mediaCode mediaCodeValue mediaCodeCookie campaignId campaignAction internalSearch customSid customEid cookieDomain cookieEidTimeout cookieSidTimeout forceNewSession xwtip xwtua xwtrq xwteid xwtstt mediaCodeFrames framesetReferrer forceHTTPS secureConfig heatmap pixelSampling form formFullContent formAnonymous disableOverlayView beforeSendinfoPixel afterSendinfoPixel beforeUnloadPixel afterUnloadPixel xlc xlct xlcv ignorePrerendering isIE isOpera isSafari isChrome isFirefox email emailRID emailOptin firstName lastName telefon gender birthday birthdayJ birthdayM birthdayD country city postalCode street streetNumber validation fileSuffix dynamicParameters numberSearchResults errorMessages loginStatus pixelVersion trackingPlatform npsScore npsScoreFeedback productLabel productMainCategory productSubCategory productManufacturer productShortDescription productLongDescription paymentMethod shippingService shippingSpeed shippingCosts grossMargin orderStatus productVariant productSoldOut paywall articleTitle paywallUser pageMainCategory pageSubCategory pageAuthor contentTags pageTitle pageType pageLength daysSincePublication testVariant testExperiment".split(" ");
this.cookie=g.cookie?g.cookie:h.cookie?h.cookie:"3";this.optoutName=g.optoutName?g.optoutName:h.optoutName?h.optoutName:"webtrekkOptOut";this.paramFirst=g.paramFirst?g.paramFirst:h.paramFirst?h.paramFirst:"";this.maxRequestLength=g.maxRequestLength?g.maxRequestLength:h.maxRequestLength?h.maxRequestLength:7168;this.plugins=g.plugins&&""!=g.plugins?g.plugins:h.plugins&&""!=h.plugins?h.plugins:"Adobe Acrobat;Windows Media Player;Shockwave Flash;RealPlayer;QuickTime;Java;Silverlight".split(";");"string"==
typeof this.plugins&&(this.plugins=this.plugins.split(";"));this.heatmapRefpoint=g.heatmapRefpoint?g.heatmapRefpoint:h.heatmapRefpoint?h.heatmapRefpoint:"wt_refpoint";this.linkTrackAttribute=g.linkTrackAttribute?g.linkTrackAttribute:h.linkTrackAttribute?h.linkTrackAttribute:"name";this.delayLinkTrack=g.delayLinkTrack?g.delayLinkTrack:h.delayLinkTrack?h.delayLinkTrack:!1;this.delayLinkTrackTime=g.delayLinkTrackTime?g.delayLinkTrackTime:h.delayLinkTrackTime?h.delayLinkTrackTime:200;this.noDelayLinkTrackAttribute=
g.noDelayLinkTrackAttribute?g.noDelayLinkTrackAttribute:h.noDelayLinkTrackAttribute?h.noDelayLinkTrackAttribute:!1;this.formAttribute=g.formAttribute?g.formAttribute:h.formAttribute?h.formAttribute:"name";this.formFieldAttribute=g.formFieldAttribute?g.formFieldAttribute:h.formFieldAttribute?h.formFieldAttribute:"name";this.formValueAttribute=g.formValueAttribute?g.formValueAttribute:h.formValueAttribute?h.formValueAttribute:"value";this.formFieldDefaultValue=g.formFieldDefaultValue?g.formFieldDefaultValue:
h.formFieldDefaultValue?h.formFieldDefaultValue:{};this.formPathAnalysis=g.formPathAnalysis?g.formPathAnalysis:h.formPathAnalysis?h.formPathAnalysis:!1;this.reporturl=g.reporturl?g.reporturl:h.reporturl?h.reporturl:"report2.webtrekk.de/cgi-bin/wt";this.updateCookie=g.updateCookie?g.updateCookie:h.updateCookie?h.updateCookie:!0;this.executePluginFunction=g.executePluginFunction?g.executePluginFunction:h.executePluginFunction?h.executePluginFunction:"";this.eid=this.optOut=this.deactivateRequest=this.deactivatePixel=
!1;this.cdb={};this.cdbData=[];this.linktrackOut=this.cookieOne=this.sampleCookieString=this.completeRequest=this.lastVisitContact=this.firstVisitContact=!1;this.linktrackNamedlinksOnly=!0;this.sentFullPixel=this.ccParams=!1;this.sentCampaignIds={};this.config=this.browserLang=this.formSubmit=this.formFocus=this.formName=this.formObject=this.gatherFormsP=this.overlayOn=this.heatmapOn=this.trackingSwitchMediaCodeTimestamp=this.trackingSwitchMediaCodeValue=this.trackingSwitchMediaCode=this.wtEpEncoded=
this.wtEp=!1;this.unloadInstance=webtrekkUnloadObjects.length;this.plugin={};this.browserLang=!1;"string"==typeof navigator.language?this.browserLang=navigator.language.substring(0,2):"string"==typeof navigator.userLanguage&&(this.browserLang=navigator.userLanguage.substring(0,2));this.jsonPara={ck:["customClickParameter",{}],cp:["customParameter",{}],cs:["customSessionParameter",{}],ce:["customTimeParameter",{}],cb:["customEcommerceParameter",{}],vc:["crmCategory",{}],uc:["urmCategory",{}],ca:["productCategory",
{}],cc:["customCampaignParameter",{}],cg:["contentGroup",{}],ct:["linkId",""],ov:["orderValue",""],cr:["currency",""],oi:["orderId",""],ba:["product",""],co:["productCost",""],qn:["productQuantity",""],st:["productStatus",""],cd:["customerId",""],is:["internalSearch",""],mc:["campaignId",""],mca:["campaignAction",""]};this.generateDefaultConfig=function(a,c){for(var b=0;b<this.defaultAttribute.length;b++){var e=this.defaultAttribute[b];this[e]=a[e]?a[e]:c[e]?c[e]:!1}};this.generateDefaultConfig(g,
h);this.campaignAction=g.campaignAction?g.campaignAction:h.campaignAction?h.campaignAction:"click";"undefined"===typeof this.safetag&&(this.safetag=!1);"undefined"===typeof this.safetagInProgress&&(this.safetagInProgress=!1);"undefined"===typeof this.safetagParameter&&(this.safetagParameter={});"undefined"===typeof this.update&&(this.update=function(){});this.saveSendinfoArguments=[];this.safetagTimeoutStarted=!1;this.version="432";this.getJSON=function(a){if("string"===typeof a&&a&&"{"==a.charAt(0)&&
"}"==a.charAt(a.length-1))try{var c=(new Function("return "+a))();if("object"===typeof c)return c}catch(b){}return null};this.parseJSON=function(a,c){for(var b in a){var e=b;if("object"==typeof a[e])"undefined"!=typeof this.jsonPara[e]&&"object"!=typeof this.config[this.jsonPara[e][0]]&&(this.config[this.jsonPara[e][0]]={}),this.parseJSON(a[e],e);else if(c){if(isNaN(parseInt(e))||500>parseInt(e))this.config[this.jsonPara[c][0]][e]=a[e]}else"undefined"!=typeof this.jsonPara[e]&&(this.config[this.jsonPara[e][0]]=
a[e])}};this.getMappingParam=function(a){var c=a.split(""),b,e,d;for(b=0;b<c.length;b++)if(!isNaN(parseInt(c[b]))){e=b;break}e?(c=a.substr(0,e),d=a.substr(e,a.length-1)):c=a;return{mapping:"undefined"!=typeof this.jsonPara[c]?this.jsonPara[c][0]:!1,index:d?d:!1}};this.getConfig=function(a){for(var c={},b=0;b<this.defaultAttribute.length;b++){var e=this.defaultAttribute[b];c[e]=a?!1:this[e]}return c};(function(a){a.pageCounter=0;a.clickCounter=0;a.linkCounter=0;a.formCounter=0;a.heatmapCounter=0;a.configCounter=
0;a.getRequestCounter=function(c,b){var e=0;"after"!==b&&e++;return"undefined"!==typeof a[c+"Counter"]?(a[c+"Counter"]+=e,a[c+"Counter"]):0};a.getPluginConfig=function(c,b){return{instance:a,mode:c,type:b,requestCounter:a.getRequestCounter(c,b)}};a.executePlugin=function(c,b){if(!a.executePluginFunction||"string"!==typeof a.executePluginFunction)return!1;b=b?b:{};a.epf=!1;for(var e=a.executePluginFunction.split(";"),d=0;d<e.length;d++)e[d]&&"function"===typeof window[e[d]]&&(a.epf=window[e[d]],a.epf(c,
b));return a.epf?!0:!1};a.triggerConfigPlugins=function(c){"undefined"!==typeof a.safetag&&a.safetag&&z();a.config="object"===typeof c?c:a.getConfig();a.executePlugin(a.getPluginConfig("config","before"));"undefined"!==typeof a.safetag&&a.safetag&&z();a.executePlugin(a.getPluginConfig("config","after"))}})(f);this.checkAsynchron=function(a,c,b,e){"undefined"!=typeof window[a]?c&&c(!0,b):0>=e?c&&c(!1,b):window.setTimeout(function(){b.checkAsynchron(a,c,b,e-100)},100)};this.loadAsynchron=function(a,
c,b,e){this.include(a)&&this.checkAsynchron(c,b?b:!1,this,e?e:2E3)};this.include=function(a){if(!document.createElement)return!1;var c=document.getElementsByTagName("head").item(0),b=document.createElement("script");b.setAttribute("language","javascript");b.setAttribute("type","text/javascript");b.setAttribute("src",a);c.appendChild(b);return!0};this.indexOf=function(a,c,b){return a.indexOf(c,b?b:0)};this.wtTypeof=function(a){return"undefined"!==typeof a?1:0};this.wtLength=function(a){return"undefined"!==
typeof a?a.length:0};this.getAttribute=function(a,c){return"string"==typeof a.getAttribute(c)?a.getAttribute(c):"object"==typeof a.getAttribute(c)&&"object"==typeof a.attributes[c]&&null!=a.attributes[c]?a.attributes[c].nodeValue:""};this.getTimezone=function(){return Math.round(-1*((new Date).getTimezoneOffset()/60))};this.wtHref=function(){return"undefined"!==typeof window.wtLocationHref?window.wtLocationHref:this.wtLocation().href};this.wtLocation=function(){var a=document.location;if(!document.layers&&
document.getElementById)try{a=top.document.location}catch(c){a=document.location}else a=top.document.location;return a};this.checkBrowser=function(){this.isIE=this.indexOf(navigator.appName,"Microsoft")?!1:!0;this.isIE||(this.isOpera=this.indexOf(navigator.appName,"Opera")?!1:!0,this.isOpera||(this.isSafari=-1!=navigator.vendor.toLowerCase().indexOf("apple"),this.isChrome=-1!=navigator.vendor.toLowerCase().indexOf("google"),this.isSafari||this.isChrome||(this.isFirefox=-1!=navigator.userAgent.toLowerCase().indexOf("firefox"))))};
this.checkBrowser();this.url2contentId=function(a){if(!a)return"no_content";a=/\/\/(.*)/.exec(a);return 1>a.length?"no_content":a[1].split("?")[0].replace(/\./g,"_").replace(/\//g,".").replace(/\.{2,}/g,".").toLowerCase().split(";")[0]};this.contentId=g.contentId?g.contentId:this.url2contentId(document.location.href);this.registerEvent=function(a,c,b){a.addEventListener?("webkitvisibilitychange"==c&&this.unregisterEvent(a,c,b),a.addEventListener(c,b,!1)):a.attachEvent&&("beforeunload"!=c&&"webkitvisibilitychange"!=
c||this.unregisterEvent(a,c,b),a.attachEvent("on"+c,b))};this.unregisterEvent=function(a,c,b){a.removeEventListener?a.removeEventListener(c,b,!1):a.detachEvent&&a.detachEvent("on"+c,b)};this.maxlen=function(a,c){return a&&a.length>c?a.substring(0,c-1):a};this.wtEscape=function(a){try{return encodeURIComponent(a)}catch(c){return escape(a)}};this.wtUnescape=function(a){try{return decodeURIComponent(a)}catch(c){return unescape(a)}};this.decrypt=function(a){var c="";if(a)try{c=this.wtUnescape(a.replace(/([0-9a-fA-F][0-9a-fA-F])/g,
"%$1"))}catch(b){}return c};this.checkSC=function(a){if("string"!=typeof this.secureConfig)return!1;for(var c=this.secureConfig.split(";"),b=0;b<c.length;b++)if(c[b]==a)return!0;return!1};(function(a){a.getexpirydate=function(a){var b=new Date,e=b.getTime();b.setTime(e+6E4*a);return b.toUTCString()};a.setCookie=function(c,b,e){var d=document.location.hostname,l=!1;-1===d.search(/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$/)&&(d=document.location.hostname.split("."),d=d[d.length-2]+"."+d[d.length-
1]);if(a.cookieDomain)for(var k=a.cookieDomain.split(";"),r=0;r<k.length;r++)if(-1!==document.location.hostname.indexOf(k[r])){d=k[r];l=!0;break}c="undefined"!==typeof e&&e?l?c+"="+escape(b)+";domain="+d+";path=/;expires="+a.getexpirydate(e):3>d.split(".")[0].length?c+"="+escape(b)+";path=/;expires="+a.getexpirydate(e):c+"="+escape(b)+";domain="+d+";path=/;expires="+a.getexpirydate(e):l?c+"="+escape(b)+";path=/;domain="+d:3>d.split(".")[0].length?c+"="+escape(b)+";path=/":c+"="+escape(b)+";path=/;domain="+
d;document.cookie=c};a.getCookie=function(a){for(var b=document.cookie.split(";"),e=0;e<b.length;e++){var d=b[e].substr(0,b[e].indexOf("=")),l=b[e].substr(b[e].indexOf("=")+1),d=d.replace(/^\s+|\s+$/g,"");if(d==a)return unescape(l)}return""}})(f);if(this.optOut=this.getCookie(this.optoutName)?!0:!1)this.deactivatePixel=!0;this.urlParam=function(a,c,b){if(!a||null===a||"undefined"===typeof a)return b;var e=[];0<a.indexOf("?")&&(e=a.split("?")[1].replace(/&amp;/g,"&").split("#")[0].split("&"));for(a=
0;a<e.length;a++)if(0==e[a].indexOf(c+"="))return this.wtUnescape(e[a].substring(c.length+1).replace(/\+/g,"%20"));return b};this.allUrlParam=function(a,c){if(this.mediaCodeFrames&&""!=this.mediaCodeFrames){for(var b=this.mediaCodeFrames.split(";"),e=0;e<b.length;e++){var d=!1;try{d=(new Function("return "+b[e]))()}catch(l){}if(d&&(d!=top&&d.location)&&(d=this.urlParam(d.location.href,a,c),d!=c))return d}return c}b="";try{b=top.location.href}catch(k){b=document.location.href}return this.urlParam(b,
a,c)};this.plugInArray=function(a,c){if("object"!=typeof a)return!1;for(var b=0;b<a.length;b++){var e=RegExp(a[b].toLowerCase(),"g");if(-1!=c.toLowerCase().search(e))return a[b]}return!1};this.quicksend=function(a,c,b){if(!this.trackDomain||!this.trackId||this.deactivatePixel||this.deactivateRequest)this.deactivateRequest=!1;else{b||(b="wt"+(this.fileSuffix?".pl":""));"undefined"===typeof this.requestTimeout&&(this.requestTimeout=5);this.geid&&(c="&geid="+this.geid+c);this.feid&&(c="&feid="+this.feid+
c);this.cdbeid&&(c="&cdbeid="+this.cdbeid+c);"1"==this.cookie&&(c="&eid="+this.eid+"&one="+(this.cookieOne?"1":"0")+"&fns="+(this.forceNewSession?"1":"0")+c);"1"!=this.cookie&&(this.wtTypeof(this.cookieEidTimeout)||this.wtTypeof(this.cookieSidTimeout))&&(this.wtTypeof(this.cookieEidTimeout)&&""!=this.cookieEidTimeout&&(c="&cet="+this.cookieEidTimeout+c),this.wtTypeof(this.cookieSidTimeout)&&""!=this.cookieSidTimeout&&(c="&cst="+this.cookieSidTimeout+c));0<this.pixelSampling&&(c+="&ps="+this.pixelSampling);
c="&tz="+this.getTimezone()+c;a="//"+this.trackDomain+"/"+this.trackId+"/"+b+"?p="+this.version+","+a+c+"&eor=1";if(this.tabBrowsing)this.sendTabBrowsingPixel(a,b);else if(!this.ignorePrerendering&&this.isChrome&&"undefined"!==typeof document.webkitHidden)if("object"!==typeof this.prerendering&&(this.prerendering=[]),document.webkitHidden){this.prerendering.push(a);var e=this;this.registerEvent(document,"webkitvisibilitychange",function(){e.sendPrerendering()})}else this.sendPixel(a,b);else this.sendPixel(a,
b);"hm"!=b&&"hm.pl"!=b&&(this.forceNewSession=this.cookieOne=!1,this.sentFullPixel=1)}};this.sendPrerendering=function(){if(!document.webkitHidden){for(var a=0;a<this.prerendering.length;a++)this.sendPixel(this.prerendering[a]);this.prerendering=[]}};(function(a){a.simulatedRequestTimeout="undefined"!==typeof g.simulatedRequestTimeout?g.simulatedRequestTimeout:"undefined"!==typeof h.simulatedRequestTimeout?h.simulatedRequestTimeout:500;a.replaceMutatedVowel="undefined"!==typeof g.replaceMutatedVowel?
g.replaceMutatedVowel:"undefined"!==typeof h.replaceMutatedVowel?h.replaceMutatedVowel:!1;a.sendPixel=function(c,b){if(a.replaceMutatedVowel){for(var e=[[/%C3%84/g,"ae"],[/%C3%A4/g,"ae"],[/%C4/g,"ae"],[/%E4/g,"ae"],[/%C3%96/g,"oe"],[/%C3%B6/g,"oe"],[/%D6/g,"oe"],[/%F6/g,"oe"],[/%C3%9C/g,"ue"],[/%C3%BC/g,"ue"],[/%DC/g,"ue"],[/%FC/g,"ue"],[/%C3%9F/g,"ss"],[/%DF/g,"ss"]],d=c,l=0,k=e.length;l<k;l++)d=d.replace(e[l][0],e[l][1]);c=d.toLowerCase()}a.completeRequest=c.split("?")[1];e=-1!==c.indexOf("&ct=")?
"link":-1!==c.indexOf("&fn=")?"form":-1!==c.indexOf("&mi=")?"media":-1!==c.indexOf("/hm")?"heatmap":-1!==c.indexOf("/cdb")?"cdb":-1!==c.indexOf("/ce")?"independent":-1!==c.indexOf("/re")?"redirect":"page";c=a.maxlen(c,a.maxRequestLength);!a.isFirefox||"link"!==e&&"form"!==e?a.sendPixelImage(c,b,e):a.sendPixelElement(c,b,e)};a.sendPixelImage=function(c,b,e){var d="https:"==window.document.location.protocol?"https:":"http:";a.forceHTTPS&&(d="https:");0!==c.search(/https:|http:/)&&(c=d+c);if("hm"==b||
"hm.pl"==b)c+="&hm_ts="+(new Date).getTime();if("function"!==typeof l)var l=function(){return document.createElement("img")};if("undefined"===typeof k)var k=[];b=k.length;k[b]=new l;(function(b,c,d){var e=!1,k=function(d,k){if(!e){e=!0;var l=(new Date).getTime()-c;b&&d&&a.executePlugin({instance:a,mode:k,type:d,requestCounter:0},{status:d,time:l,request:b.src,item:b})}};b.onerror=function(){k("error",d)};b.onload=function(){k("success",d)};window.setTimeout(function(){k("timeout",d)},a.simulatedRequestTimeout)})(k[b],
(new Date).getTime(),e);k[b].src=c};a.createPixelElement=function(a){a=a.replace(/'/g,"%27");var b=document.createElement("div");b.style.width="0px";b.style.height="0px";b.style.backgroundImage="url('"+a+"')";window.setTimeout(function(){b.parentElement.removeChild(b)},5E3);return b};a.sendPixelElement=function(c,b,e){var d="https:"==window.document.location.protocol?"https:":"http:";a.forceHTTPS&&(d="https:");0!==c.search(/https:|http:/)&&(c=d+c);if("hm"==b||"hm.pl"==b)c+="&hm_ts="+(new Date).getTime();
if("undefined"===typeof a.sendPixelObject||null===a.sendPixelObject)(b=document.getElementById("webtrekk-image"))&&null!==b?a.sendPixelObject=b:(a.sendPixelObject=document.createElement("div"),a.sendPixelObject.id="webtrekk-image",a.sendPixelObject.style.width="0px",a.sendPixelObject.style.height="0px",a.sendPixelObject.style.overflow="hidden",b=null,"object"===typeof document.body?b=document.body:"object"===typeof document.getElementsByTagName("body")[0]&&(b=document.getElementsByTagName("body")[0]),
b&&null!==b?b.appendChild(a.sendPixelObject):(a.sendPixelObject=null,a.sendPixelImage(c,"wt"+(a.fileSuffix?".pl":""),e)));null!==a.sendPixelObject&&a.sendPixelObject.appendChild(a.createPixelElement(c))}})(f);(function(a){a.PredefinedParameter=function(){var a=this,b="customClickParameter customSessionParameter customCampaignParameter customEcommerceParameter customParameter crmCategory urmCategory contentGroup productCategory".split(" "),e={numberSearchResults:[b[4],771],errorMessages:[b[4],772],
loginStatus:[b[1],800],pixelVersion:[b[1],801],trackingPlatform:[b[1],802],npsScore:[b[6],850],npsScoreFeedback:[b[6],851],productLabel:[b[8],870],productMainCategory:[b[8],871],productSubCategory:[b[8],872],productManufacturer:[b[8],873],productShortDescription:[b[8],874],productLongDescription:[b[8],875],paymentMethod:[b[3],761],shippingService:[b[3],762],shippingSpeed:[b[3],763],shippingCosts:[b[3],764],grossMargin:[b[3],765],orderStatus:[b[3],766],productVariant:[b[3],767],couponValue:[b[3],563],
productSoldOut:[b[3],760],paywall:[b[4],773],articleTitle:[b[4],774],paywallUser:[b[6],852],pageMainCategory:[b[7],880],pageSubCategory:[b[7],881],pageAuthor:[b[7],882],contentTags:[b[4],775],pageTitle:[b[4],776],pageType:[b[4],777],pageLength:[b[4],778],daysSincePublication:[b[4],779],testVariant:[b[4],781],testExperiment:[b[4],782],email:[b[6],700],emailRID:[b[6],701],emailOptin:[b[6],702],firstName:[b[6],703],lastName:[b[6],704],telefon:[b[6],705],gender:[b[6],706],birthday:[b[6],707],country:[b[6],
708],city:[b[6],709],postalCode:[b[6],710],street:[b[6],711],streetNumber:[b[6],712],validation:[b[6],713]},d={},l=function(){for(var a=0;a<b.length;a++)d[b[a]]={}};l();this.list={};this.clear=function(){d={};a.list={};l()};this.get=function(b){b="all"===b?d:"undefined"!==typeof a.list[b]?a.list[b]:null;return b};this.put=function(b,l){if(l&&"undefined"!==typeof e[b]){var f=e[b];d[f[0]][f[1]]=l;a.list[b]=l}return a};this.remove=function(b){var l=null;if("undefined"!==typeof e[b]){var f=e[b];"undefined"!==
typeof d[f[0]]&&"undefined"!==typeof d[f[0]][f[1]]&&(l=d[f[0]][f[1]],delete d[f[0]][f[1]]);delete a.list[b]}return l}};a.checkCustomParameter=function(c,b){var e="";if("object"==typeof c)for(var d in c){var l=d;!isNaN(parseInt(l))&&(a.wtTypeof(c[l])&&"string"===typeof c[l]&&""!==c[l])&&(a.checkSC("custom")&&(c[l]=a.decrypt(c[l])),-1==a.paramFirst.indexOf(b+l+";")&&(e+="&"+b+l+"="+a.wtEscape(c[l])))}return e};a.mergeCustomParameter=function(a,b){a||(a={});for(var e in b)a[e]=b[e];return a}})(f);this.send=
function(a,c,b){if("link"==c||"click"==c)this.config.linkId=a;this.config.contentId=this.config.contentId?this.config.contentId:this.contentId;var e=!c||"link"!=c&&"click"!=c?a?a:this.config.contentId:this.config.contentId;e||(e="no_content");a="";var e=this.wtEscape(e)+",1,",e=e+this.baseparams(),d=navigator.plugins.length,l="";if(0<d){for(var k=[],f=0;f<d;f++)navigator.plugins&&"Microsoft Internet Explorer"!=navigator.appName&&(l="Shockwave Flash"==navigator.plugins[f].name?navigator.plugins[f].description:
navigator.plugins[f].name,(l=this.plugInArray(this.plugins,l))&&!this.plugInArray(k,l)&&k.push(l));l=k.join("|")}if(this.paramFirst)for(d=this.paramFirst.split(";"),f=0;f<d.length;f++){var n=this.getMappingParam(d[f]),k=n.mapping,n=n.index;k&&(n?this.config[k]&&("undefined"!=typeof this.config[k][n]&&this.config[k][n])&&(a+="&"+d[f]+"="+this.wtEscape(this.config[k][n])):this.config[k]&&(a+="&"+d[f]+"="+this.wtEscape(this.config[k])))}if("string"===typeof b&&""!==b)for(var g=b.split(/;/),h=0;h<g.length;h++){if(this.wtTypeof(g[h])){var q=
g[h].split(/=/);this.checkSC("custom")&&(q[1]=this.decrypt(q[1]));q[1]=this.wtEscape(q[1]);a+="&"+q[0]+"="+q[1]}}else{this.wtEpEncoded=!1;n=new this.PredefinedParameter;for(q in this.config)n.put(q,this.config[q]);var p=n.get("all");this.config.customParameter=this.mergeCustomParameter(this.config.customParameter,p.customParameter);q=this.checkCustomParameter(this.config.customParameter,"cp");this.config.customSessionParameter=this.mergeCustomParameter(this.config.customSessionParameter,p.customSessionParameter);
b=this.checkCustomParameter(this.config.customSessionParameter,"cs");f=this.checkCustomParameter(this.config.customTimeParameter,"ce");d=this.checkCustomParameter(this.cdb,"cdb");this.config.customEcommerceParameter=this.mergeCustomParameter(this.config.customEcommerceParameter,p.customEcommerceParameter);k=this.checkCustomParameter(this.config.customEcommerceParameter,"cb");this.config.orderValue&&-1==this.paramFirst.indexOf("ov;")&&(a=this.checkSC("order")?a+("&ov="+this.wtEscape(this.decrypt(this.config.orderValue))):
a+("&ov="+this.wtEscape(this.config.orderValue)));this.config.currency&&-1==this.paramFirst.indexOf("cr;")&&(a=this.checkSC("order")?a+("&cr="+this.wtEscape(this.decrypt(this.config.currency))):a+("&cr="+this.wtEscape(this.config.currency)));this.config.orderId&&-1==this.paramFirst.indexOf("oi;")&&(a+="&oi="+this.wtEscape(this.config.orderId));this.config.product&&(-1==this.paramFirst.indexOf("ba;")&&(a+="&ba="+this.wtEscape(this.config.product)),this.config.productCost&&-1==this.paramFirst.indexOf("co;")&&
(a+="&co="+this.wtEscape(this.config.productCost)),this.config.productQuantity&&-1==this.paramFirst.indexOf("qn;")&&(a+="&qn="+this.wtEscape(this.config.productQuantity)),this.config.productCategory=this.mergeCustomParameter(this.config.productCategory,p.productCategory),a+=this.checkCustomParameter(this.config.productCategory,"ca"),this.config.productStatus&&-1==this.paramFirst.indexOf("st;")&&(a+="&st="+this.wtEscape(this.config.productStatus)));var v=x("wt_cd","(.*)");this.config.customerId||(this.config.customerId=
v);this.config.customerId&&-1==this.paramFirst.indexOf("cd;")&&(a+="&cd="+this.wtEscape(this.config.customerId));this.config.crmCategory=this.mergeCustomParameter(this.config.crmCategory,p.crmCategory);a+=this.checkCustomParameter(this.config.crmCategory,"vc");null===n.get("birthday")&&(this.config.birthdayJ&&this.config.birthdayM&&this.config.birthdayD)&&n.put("birthday",this.config.birthdayJ+this.config.birthdayM+this.config.birthdayD);null!==n.get("telefon")&&n.put("telefon",n.get("telefon").replace(/\W|_/g,
""));this.config.urmCategory=this.mergeCustomParameter(this.config.urmCategory,p.urmCategory);a+=this.checkCustomParameter(this.config.urmCategory,"uc");this.browserLang&&(a+="&la="+this.wtEscape(this.browserLang));this.config.contentGroup=this.mergeCustomParameter(this.config.contentGroup,p.contentGroup);a+=this.checkCustomParameter(this.config.contentGroup,"cg");n="";this.config.campaignId&&(this.config.campaignId in this.sentCampaignIds?this.config.campaignId="ignore%3Dignore":this.sentCampaignIds[this.config.campaignId]=
!0,-1==this.paramFirst.indexOf("mc;")&&(a+="&mc="+this.wtEscape(this.config.campaignId)),-1==this.paramFirst.indexOf("mca;")&&(a+="&mca="+(this.config.campaignAction?this.config.campaignAction.substring(0,1):"c")));this.config.customCampaignParameter=this.mergeCustomParameter(this.config.customCampaignParameter,p.customCampaignParameter);n+=this.checkCustomParameter(this.config.customCampaignParameter,"cc");this.trackingSwitchMediaCode&&(a+="&tmc="+this.wtEscape(this.trackingSwitchMediaCode));this.trackingSwitchMediaCodeValue&&
(a+="&tmcv="+this.wtEscape(this.trackingSwitchMediaCodeValue));this.trackingSwitchMediaCodeTimestamp&&(a+="&tmct="+this.wtEscape(this.trackingSwitchMediaCodeTimestamp));"object"==typeof wt_ts&&"undefined"!=typeof wt_ts.trackingSwitchMediaCode&&(a+="&tmc="+this.wtEscape(wt_ts.trackingSwitchMediaCode));"object"==typeof wt_ts&&"undefined"!=typeof wt_ts.trackingSwitchMediaCodeValue&&(a+="&tmcv="+this.wtEscape(wt_ts.trackingSwitchMediaCodeValue));"object"==typeof wt_ts&&"undefined"!=typeof wt_ts.trackingSwitchMediaCodeTimestamp&&
(a+="&tmct="+this.wtEscape(wt_ts.trackingSwitchMediaCodeTimestamp));p="";"undefined"!=typeof wt_vt&&(h=wt_vt);this.wtTypeof(h)||(h=this.urlParam(location.href,"wt_vt",!1));if(h)for(var v=this.getCookie("wt_vt").split(";"),m=0;m<v.length;m++)-1!=v[m].indexOf(h+"v")&&(p="&wt_vt="+v[m].split("t")[0].split("v")[1]);p&&(a+=p);this.config.internalSearch&&-1==this.paramFirst.indexOf("is;")&&(a+="&is="+this.wtEscape(this.maxlen(this.wtUnescape(this.config.internalSearch),255)));if(this.config.dynamicParameters)for(g in this.config.dynamicParameters)h=
g+"",this.config.dynamicParameters[h]&&(a="object"===typeof this.config.dynamicParameters[h]?a+this.checkCustomParameter(this.config.dynamicParameters,h):a+("&"+g+"="+this.wtEscape(this.config.dynamicParameters[h])));q&&(a+=q);n&&(a+=n);f&&(a+=f);k&&(a+=k);b&&(a+=b);d&&(a+=d);this.wtTypeof(this.config.customSid)&&""!=this.config.customSid&&(a+="&csid="+this.config.customSid);this.wtTypeof(this.config.customEid)&&""!=this.config.customEid&&(a+="&ceid="+this.config.customEid);this.wtTypeof(this.config.xwtip)&&
""!=this.config.xwtip&&(a+="&X-WT-IP="+this.wtEscape(this.config.xwtip));this.wtTypeof(this.config.xwtua)&&""!=this.config.xwtua&&(a+="&X-WT-UA="+this.wtEscape(this.config.xwtua));this.wtTypeof(this.config.xwtrq)&&""!=this.config.xwtrq&&(a+="&X-WT-RQ="+this.wtEscape(this.config.xwtrq));this.wtTypeof(this.xwteid)&&""!=this.xwteid&&(a+="&X-WT-EID="+this.wtEscape(this.xwteid),this.xwteid=!1);this.wtTypeof(this.config.xwtstt)&&""!=this.config.xwtstt&&(a+="&X-WT-STT="+this.wtEscape(this.config.xwtstt));
!this.sentFullPixel&&this.firstVisitContact&&(a+="&fvc="+this.firstVisitContact);!this.sentFullPixel&&this.lastVisitContact&&(a+="&lvc="+this.lastVisitContact)}a+="&pu="+this.wtEscape(document.location.href.split("#")[0]);this.config.linkId&&this.config.customClickParameter&&(a+=this.checkCustomParameter(this.config.customClickParameter[this.config.linkId]?this.config.customClickParameter[this.config.linkId]:this.config.customClickParameter,"ck"),this.ccParams=!1);this.config.xlc&&this.config.xlct&&
(""!=this.config.xlc||""!=this.config.xlct)&&(g="",g=this.config.xlcv?this.getExtLifeCycles(this.config.xlc,this.config.xlct,this.config.xlcv):this.getExtLifeCycles(this.config.xlc,this.config.xlct),a+=g);this.config.contentId||this.config.linkId||(this.config.contentId=this.contentId,this.config.linkId="wt_ignore");this.config.linkId?(this.wtEp=a,this.wtEpEncoded=!0,y("noForm",c)):("1"==this.cookie?this.cookieOne&&(a+="&np="+this.wtEscape(l)):a+="&np="+this.wtEscape(l),this.quicksend(e,a))};this.sendinfo_media=
function(a,c,b,e,d,l,k,f){this.wtTypeof(wt_sendinfo_media)&&wt_sendinfo_media(a,c,b,e,d,l,k,f,this.unloadInstance)};this.getExtLifeCycles=function(a,c,b){for(var e="",d={},l=a.split("|"),k=0;k<l.length;k++){for(var f=l[k].split(";"),n=0;n<f.length;n++)e=0==n?e+this.wtEscape(f[n]):e+f[n],e+=";";e=e.substr(0,e.length-1);e+="|"}e=e.substr(0,e.length-1);d.xlcl=this.wtEscape(a.split("|").length);d.xlct=this.wtEscape(c);"undefined"!=typeof b&&(d.xlcv=this.wtEscape(b));d.xlc=this.wtEscape(e);a="";for(var g in d)a+=
"&"+k+"="+d[g];return a};this.isOwnDomain=function(a){var c="";if(this.domain)if(0==this.domain.toUpperCase().indexOf("REGEXP:")){if(c=RegExp(this.domain.substring(7),"i"),c.test(this.getDomain(a)))return!0}else{c=this.domain.split(";");a=this.getDomain(a);for(var b=0;b<c.length;b++)if(a==c[b])return!0}return!1};this.getDomain=function(a){if("string"!=typeof a)return"";a=this.wtUnescape(a);a=a.split("://")[1];var c=RegExp("^(?:[^/]+://)?([^/:]+)","g");return"undefined"!=typeof a&&(a=a.match(c),a[0])?
a[0].toLowerCase():""};this.baseparams=function(){var a=screen.width+"x"+screen.height+","+("Netscape"!=navigator.appName?screen.colorDepth:screen.pixelDepth)+",",a=a+(!0==navigator.cookieEnabled?"1,":!1==navigator.cookieEnabled?"0,":-1!=document.cookie.indexOf("=")?"1,":"0,"),a=a+((new Date).getTime()+","),c="0",b=x("wt_ref","(.*)");f.framesetReferrer?c=f.wtEscape(f.framesetReferrer):""!=f.getCookie("wt_ref")?(c=f.wtEscape(f.getCookie("wt_ref")),f.setCookie("wt_ref","",-3600)):b?c=f.wtEscape(b):
0<document.referrer.length&&(c=f.wtEscape(document.referrer));f.sentFullPixel?c="2":f.isOwnDomain(c)&&(c="1");b=0;if(!document.layers&&document.getElementById)try{b=top.window.innerHeight}catch(e){}else b=top.window.innerHeight;if(!b)try{b=top.document.documentElement.clientHeight}catch(d){}if(!b)try{b=top.document.body.clientHeight}catch(l){}"undefined"==typeof b&&(b=-1);var k;k=0;if(!document.layers&&document.getElementById)try{k=top.window.innerWidth}catch(r){}else k=top.window.innerWidth;if(!k)try{k=
top.document.documentElement.clientWidth}catch(n){}if(!k)try{k=top.document.body.clientWidth}catch(g){}"undefined"==typeof k&&(k=-1);b&&b>screen.height&&(b=screen.height);k&&k>screen.width&&(k=screen.width);a=a+c+(","+k+"x"+b);return a+=","+(navigator.javaEnabled()?"1":"0")};this.getMediaCode=function(a){if(!a){if(!this.mediaCode)return;a=this.mediaCode}var c=[];a=a.split(";");var b=0,e=[];this.mediaCodeValue&&(c=this.mediaCodeValue.split(";"));for(var d=0;d<a.length;d++){var f=this.allUrlParam(a[d],
"");if(this.mediaCodeCookie){var k=!1,r=(this.trackId+"").split(",")[0],n=this.getCookie("wt_mcc_"+r),g;g=a[d]+"_"+f;for(var h=0,q=g.length,p=void 0,m=0;m<q;m++)p=g.charCodeAt(m),h=(h<<5)-h+p,h&=h;g=h>1E15-1?"0":h+"";-1===n.indexOf(","+g+",")&&f?(e.push(a[d]+this.wtEscape("="+f)),k=!0):b++;k&&(f="","eid"==this.mediaCodeCookie&&(f=2592E3),this.setCookie("wt_mcc_"+r,n+","+g+",",f))}else"undefined"!==typeof c&&"undefined"!==typeof c[d]&&""!==c[d]?e.push(a[d]+this.wtEscape("="+c[d])):""!==f&&e.push(a[d]+
this.wtEscape("="+f))}a.length===b&&0!==a.length&&e.push("ignore%3Dignore");this.config.campaignId=e.join(";")};this.searchContentIds=function(){var a=0,c=0;this.contentIds=this.wtEscape(this.contentId.split(";")[0]);do{a++;var b=this.urlParam(document.location.href,"wt_contentId"+a,!1);b&&(this.contentIds+="&wt_contentId"+a+"="+this.wtEscape(b),c++)}while(c>=a)};var w=function(a){var c=f.reporturl;null!==a.match(/^(http[s]?:\/\/)?(report\d+|analytics)\.webtrekk\.(com|de).*$/)&&(c=a.split("/"),c.pop(),
c=c.join("/"));return c};this.startHeatmapOrOverlay=function(a,c){this.searchContentIds();this.urlParam(this.wtHref(),"wt_reporter",!1)?this.reporturl=w(this.urlParam(this.wtHref(),"wt_reporter",!1)):this.getCookie("wt_overlayFrame")&&(this.reporturl=w(this.getCookie("wt_overlayFrame")));-1===this.reporturl.search(/http|https/)&&(this.reporturl=document.location.protocol+"//"+this.reporturl);this.contentIds&&this.include(this.reporturl+"/"+a+".pl?wt_contentId="+this.contentIds+"&x="+(new Date).getTime())&&
("heatmap"==a&&(-1!=navigator.userAgent.indexOf("MSIE 6")&&-1!=navigator.userAgent.indexOf("Windows NT 5.0"))&&alert("Click OK to start heatmap."),"complete"!=document.readyState?this.registerEvent(window,"load",c):c())};this.heatmapOn=0<=this.wtHref().indexOf("wt_heatmap=1");this.overlayOn=0<=this.wtHref().indexOf("wt_overlay=1")||0<=document.cookie.indexOf("wt_overlay=1");0<=this.wtHref().indexOf("wt_overlay=0")&&(this.overlayOn=!1,this.setCookie("wt_overlay","",-1));this.heatmapTrackInit=function(){for(var a=
!1,c=0;c<webtrekkHeatmapObjects.length;c++)this==webtrekkHeatmapObjects[c]&&(a=!0);!a&&(this.heatmap&&"1"==this.heatmap)&&(webtrekkHeatmapObjects.push(this),this.registerEvent(document,"mousedown",s),this.registerEvent(document,"touchstart",s))};this.heatmapTrackInit();this.heatmapOn&&!this.disableOverlayView&&this.startHeatmapOrOverlay("heatmap",u);this.overlayOn&&!this.disableOverlayView&&(this.setCookie("wt_overlay","1"),this.startHeatmapOrOverlay("overlay",m));this.setPixelSampling=function(a){a||
(a=this.pixelSampling);for(var c=this.trackId.split(",")[0],b=this.getCookie("wt3_sample").split(";"),e=!1,d=0;d<b.length;d++)-1!=this.indexOf(b[d],c+"|"+a)?e=!0:-1!=this.indexOf(b[d],c+"|")&&(b[d]="");d=6;this.cookieEidTimeout&&(d=this.cookieEidTimeout);e?(b=b.join(";"),this.setCookie("wt3_sample",b,43200*d)):(Math&&Math.random&&0==parseInt(Math.random()*a)?b.push(c+"|"+a+"|1"):b.push(c+"|"+a+"|0"),this.setCookie("wt3_sample",b.join(";"),43200*d),b=this.getCookie("wt3_sample"));-1==this.indexOf(b,
c+"|"+a+"|1")&&(this.deactivatePixel=!0)};this.pixelSampling&&!this.optOut&&this.setPixelSampling();(function(a){var c=function(){var b=a.trackId.split(",")[0],d=0===a.cookieEidTimeout?a.cookieEidTimeout:a.cookieEidTimeout?a.cookieEidTimeout:6,c=a.generateEid(),k="",f="",n=[],g=-1,h="",q=!1,p=c,m=!1,s=function(){d?a.setCookie("wt3_eid",n.join(";"),43200*d):a.setCookie("wt3_eid",n.join(";"))},w=function(a){if(a&&"2"==a.substring(0,1)){a=parseInt(a.substring(1,11)+"000");a=new Date(a);var b=a.getFullYear()+
"",b=b+(10>a.getMonth()+1?"0":""),b=b+(a.getMonth()+1),b=b+(10>a.getDate()?"0":""),b=b+a.getDate(),b=b+(10>a.getHours()?"0":""),b=b+a.getHours(),b=b+(10>a.getMinutes()?"0":"");return b+=a.getMinutes()}return""};(function(){n=a.getCookie("wt3_eid").split(";");for(var d=0;d<n.length;d++)if(-1!==n[d].indexOf(b+"|")){g=d;f=n[d];h=f.replace(b+"|","").split("#")[0];-1!==f.indexOf("#")&&(p=f.replace(b+"|","").split("#")[1]);break}})();k=x("wt_eid","^[0-9]{19}$");h?(k&&(n[g]=b+"|"+k,h=k,a.updateCookie=!0),
"undefined"!==typeof window.wt_mcp_eid&&(q=!0),-1===n[g].indexOf("#")?n[g]+="#"+c:n[g]=f.replace(/#[0-9]{19}/g,"#"+c),a.updateCookie?s():m=p=!1):("string"===typeof window.wt_mcp_eid&&-1!==window.wt_mcp_eid.indexOf(b+"|")?(h=window.wt_mcp_eid.replace(b+"|",""),q=!0):k?h=k:(h=a.generateEid(),q=!0),n.push(b+"|"+h+"#"+c),s());a.updateCookie&&(p=w(p),m=w(h));this.getId=function(){return h};this.getUrlId=function(){return k};this.getLastVisitContact=function(){return p};this.getFirstVisitContact=function(){return m};
this.getCookieOne=function(){return q}},b=function(){var b=a.trackId.split(",")[0],d=[],c="";(function(){d=a.getCookie("wt3_sid").split(";");for(var k=0;k<d.length;k++)if(-1!==d[k].indexOf(b)){c=d[k];break}})();c||d.push(b);a.setCookie("wt3_sid",d.join(";"));this.getId=function(){return c}};a.zeroPad=function(a,b){for(var c="",k=0;k<=b;k++)c+="0";c+=a;return c.substring(c.length-b,c.length)};a.generateEid=function(){return"2"+a.zeroPad(Math.floor((new Date).getTime()/1E3),10)+a.zeroPad(Math.floor(1E6*
Math.random()),8)};a.firstParty=function(){var e=new c,d=new b;a.eid=e.getId();a.cookieOne=e.getCookieOne();d.getId()||(e.getId()!==e.getUrlId()&&(a.forceNewSession=!0),a.firstVisitContact=e.getFirstVisitContact(),a.lastVisitContact=e.getLastVisitContact())}})(f);for(var C=!1,B=0;B<webtrekkUnloadObjects.length;B++)this==webtrekkUnloadObjects[B]&&(C=!0);C||webtrekkUnloadObjects.push(this);var z=function(){var a=[],c;for(c in f.safetagParameter){var b=c;if("executePluginFunction"==b)f.executePluginFunction+=
f.safetagParameter[b],f.safetagParameter[b]="";else if("object"===typeof f.safetagParameter[b]){"object"!==typeof f[b]&&(f[b]={});for(var e in f.safetagParameter[b]){var d=e;f[b][d]=f.safetagParameter[b][d]}}else f[b]=f.safetagParameter[b],"form"!==b&&"linkTrack"!==b&&"heatmap"!==b&&"tabBrowsing"!==b&&"execCDB"!==b&&"execRTA"!==b||a.push(b)}for(c=0;c<a.length;c++)switch(a[c]){case "form":f.formTrackInstall();break;case "linkTrack":f.linkTrackInit();break;case "heatmap":f.heatmapTrackInit();break;
case "tabBrowsing":f.startTabBrowsing();break;case "execCDB":f.startCDB();break;case "execRTA":f.startRTA()}f.safetagParameter.pixel=f},D=function(){f.safetagTimeoutStarted=!0;var a=(new Date).getTime()-f.startSafetagTimeoutDate;if(f.safetagInProgress&&a<f.safetag.timeout)window.setTimeout(function(){D()},5);else{f.safetagTimeoutStarted=!1;f.safetagInProgress=!1;a>f.safetag.timeout&&(f.xwtstt=f.safetag.timeout+"");for(a=0;a<f.saveSendinfoArguments.length;a++){var c=f.saveSendinfoArguments[a];f.sendinfo(c[0],
c[1],c[2],c[3])}f.saveSendinfoArguments=[]}};this.sendinfo=function(a,c,b,e){b=b?b:"page";-1==location.href.indexOf("fb_xd_fragment")&&(this.safetag&&z(),this.config="object"==typeof a?a:this.getConfig(),this.safetagInProgress?(a?f.saveSendinfoArguments.push([this.config,c,b,e]):f.saveSendinfoArguments.push([!1,c,b,e]),this.safetagTimeoutStarted||(this.startSafetagTimeoutDate=(new Date).getTime(),window.setTimeout(function(){D()},5))):(this.config.linkId&&(b="click",c||(c=this.config.linkId)),!1!=
this.beforeSendinfoPixel?this.beforeSendinfoPixel():this.executePlugin(this.getPluginConfig(b?b:"page","before")),this.safetag&&z(),this.optOut||this.deactivatePixel||("1"==this.cookie?this.firstParty():this.xwteid=x("wt_eid","^[0-9]{19}$")),this.config.campaignId||(!this.mediaCode||"page"!=b||this.config.linkId)||this.getMediaCode(),(""!=this.contentId||""!=c||document.layers)&&this.send(c,b,e),!1!=this.afterSendinfoPixel?this.afterSendinfoPixel():this.executePlugin(this.getPluginConfig(b?b:"page",
"after"))))};(function(a){var c=function(b,c){var d=this;d.item=c;d.href="undefined"!==typeof c.href?c.href:a.getAttribute(c,"href")?a.getAttribute(c,"href"):"";d.linkIdByNameOrId=a.getAttribute(c,"name")?a.getAttribute(c,"name"):a.getAttribute(c,"id")?a.getAttribute(c,"id"):"";d.linkId="";d.action="link";d.isDownloadFile=!1;d.linktrackOut=!1;d.isInternalLink=function(){var b;if(a.linkTrackDownloads){b=d.href.split(".");b=b.pop();for(var k=a.linkTrackDownloads.split(";"),f=0;f<k.length;f++)if(k[f]==
b){d.isDownloadFile=!0;break}}d.linktrackOut=a.domain&&!a.isOwnDomain(d.href);if(d.isDownloadFile||"_blank"===c.target)d.action="click";b=d.href;var k=b.toLowerCase(),f=b.split("#")[0],g=document.location,h=d.item,m=a.getAttribute,q=m(h,"onclick"),p=m(h,"onmousedown"),h=m(h,"ontouchstart");b=a.noDelayLinkTrackAttribute?!!a.getAttribute(c,a.noDelayLinkTrackAttribute):!(b&&!(0===k.indexOf("javascript:")||0===k.indexOf("#")||"click"===d.action||f==g.href.split("#")[0]&&-1!==b.indexOf("#")||f==g.pathname.split("#")[0]&&
-1!==b.indexOf("#")||q&&-1!==q.search(/return false[;]?$/)||p&&-1!==p.search(/return false[;]?$/)||h&&-1!==h.search(/return false[;]?$/)));return b};d.getCCParams=function(){var b="";if(a.config.customClickParameter){var c="undefined"!==typeof a.config.customClickParameter[d.linkIdByNameOrId]?a.config.customClickParameter[d.linkIdByNameOrId]:!1;c||(c=a.config.customClickParameter);var e,f;for(f in c)e=f,!isNaN(parseInt(e))&&("string"===typeof c[e]&&c[e])&&(a.checkSC("custom")&&(c[e]=a.decrypt(c[e])),
b+="&ck"+e+"="+a.wtEscape(c[e]))}return b};d.setJSONParams=function(){d.linkId||(d.linkId=a.getAttribute(c,a.linkTrackAttribute));null!==a.getJSON(d.linkId)&&(a.parseJSON(a.getJSON(d.linkId)),d.linkId=a.config.linkId)};d.getLinkId=function(){d.linkId=a.getAttribute(c,a.linkTrackAttribute);d.setJSONParams();if("link"==a.linkTrack){var b=d.href.indexOf("//");d.href=0<=b?d.href.substr(b+2):d.href;a.linkTrackPattern&&(a.linkTrackReplace||(a.linkTrackReplace=""),d.href=d.href.replace(a.linkTrackPattern,
a.linkTrackReplace));d.linkId=(d.linkId?d.linkId+".":"")+d.href.split("?")[0].split("#")[0].replace(/\//g,".");b=[];a.linkTrackParams&&(b=a.linkTrackParams.replace(/;/g,",").split(","));for(var k=0;k<b.length;k++){var f=a.urlParam(d.href,b[k],"");f&&(d.linkId+="."+b[k]+"."+f)}}return d.linkId}};a.linkTrackObject=new function(){var b=this;b.triggerObjectName="__"+(new Date).getTime()+"_"+parseInt(1E3*Math.random());var e=function(c,d){var e=d[b.triggerObjectName];a.config=a.getConfig(!0);a.config.customClickParameter=
a.customClickParameter;a.ccParams=e.getCCParams();var f=a.config.linkId=e.getLinkId();a.linktrackOut=e.linktrackOut;a.sendinfo(a.config,f,e.action)},d=function(c){a.registerEvent(c,"click",function(d){if(d.which&&1==d.which||d.button&&1==d.button)a.delayLinkTrack&&("function"===typeof d.preventDefault&&!c[b.triggerObjectName].isInternalLink())&&(d.preventDefault(),window.setTimeout(function(){document.location.href=c.href},a.delayLinkTrackTime)),e(d,c)})};b.linkTrackInit=function(){if(a.linkTrack&&
("link"==a.linkTrack||"standard"==a.linkTrack)){for(var e=!1,k=0;k<webtrekkLinktrackObjects.length;k++)a==webtrekkLinktrackObjects[k]&&(e=!0);e||webtrekkLinktrackObjects.push(a);e=0;for(k=document.links.length;e<k;e++){var f=document.links[e],h=a.getAttribute(f,a.linkTrackAttribute),g=a.getAttribute(f,"href");(a.linkTrackIgnorePattern&&g&&-1==g.search(a.linkTrackIgnorePattern)||!a.linkTrackIgnorePattern)&&("undefined"===typeof f[b.triggerObjectName]&&(h||"link"==a.linkTrack))&&(f[b.triggerObjectName]=
new c(b,f),d(f))}}}};a.linkTrackInstall=a.linkTrackObject.linkTrackInit;a.linkTrackInit=a.linkTrackObject.linkTrackInit;"complete"===document.readyState?a.linkTrackInit():a.registerEvent(window,"load",function(){a.linkTrackInit()})})(f);(function(a,c){var b=function(a,b,c){var f=null,h=b.type,g=a.getFormFieldName(b),m=a.getFormFieldValue(b);this.close=function(){null!==f&&(m=a.getFormFieldValue(b),"radio"!==h&&(window.clearInterval(f),f=null,a.formFieldData[g][c]=[h,m]),a.formFieldDataPathAnalysis.push([g,
h,m]))};this.start=function(A){null===f&&(f=window.setInterval(function(){"undefined"!==typeof b&&(b&&null!==b&&"undefined"!==typeof a.formFieldData[g])&&("string"!==typeof a.formFieldData[g][0]&&"string"!==typeof a.formFieldData[g][a.formFieldData.length-1])&&(m=a.getFormFieldValue(b),a.formFieldData[g][c]=[h,m])},50),A||delete a.formFieldDataUnused[g])}};a.formTrackObject=new function(c){var d=this;d.formObject=!1;d.formFocus=!1;d.formName=!1;d.form=a.form;d.formFieldData={};d.formFieldDataUnused=
{};d.formFieldDataPathAnalysis=[];d.triggerObjectName="__"+(new Date).getTime()+"_"+parseInt(1E3*Math.random());var f=function(a){return"hidden"!=a&&"button"!=a&&"image"!=a&&"reset"!=a&&"submit"!=a&&"fieldset"!=a},k=function(a){return"select-multiple"!=a&&"select-one"!=a&&"checkbox"!=a&&"radio"!=a},g=function(){h();if(d.formObject){var b=a.getAttribute(d.formObject,a.formAttribute);d.formName=b?b:a.contentId.split(";")[0];for(var b=0,k=d.formObject.elements,g=k.length;b<g;b++){var r=k[b],t=d.getFormFieldName(r);
if(f(r.type)&&t&&null!==t){"undefined"===typeof d.formFieldData[t]&&(d.formFieldData[t]=[]);"undefined"===typeof d.formFieldDataUnused[t]&&(d.formFieldDataUnused[t]=[]);var p=d.getFormFieldValue(r);d.formFieldData[t].push([r.type,p]);d.formFieldDataUnused[t].push([r.type,p]);t=d.formFieldData[t].length-1;"radio"===r.type&&r.checked&&m(r,!0,t);(function(b,c){a.registerEvent(b,"focus",function(){m(b,!1,c)});a.registerEvent(b,"blur",function(){f(b.type)&&(d.formObject&&b&&b&&"undefined"!==typeof b[d.triggerObjectName])&&
(b[d.triggerObjectName].close(),"radio"!==b.type&&delete b[d.triggerObjectName])})})(r,t)}}a.registerEvent(d.formObject,"submit",A);a.registerEvent(window,"beforeunload",c);a.registerEvent(window,"unload",c)}},h=function(){if(d.form&&!d.formObject)for(var b=document.forms,c=0,e=b.length;c<e;c++){var f=b[c];if(a.wtTypeof(f.elements.wt_form)){d.formObject=f;break}}},m=function(a,c,e){f(a.type)&&d.formObject&&(c||(d.formFocus=a),"undefined"===typeof a[d.triggerObjectName]&&(a[d.triggerObjectName]=new b(d,
a,e),a[d.triggerObjectName].start(c)))},A=function(b){!d.form||b.target!==d.formObject&&b.srcElement!==d.formObject||(a.formSubmit=!0)},q=function(b){var c=[];a.formFullContent&&(c=a.formFullContent.split(";"));if(a.formAnonymous||k(b.type)){for(var e=0;e<c.length;e++)if(c[e]==d.getFormFieldName(b))return!1;return!0}return!1},p=function(b,c){c||(c=b);var d=a.getAttribute(c,a.formValueAttribute).replace(/[\.|;|\|]/g,"_");return k(b.type)?a.maxlen(a.wtUnescape(c.value),110):q(b)?"anon":a.maxlen(a.wtUnescape(d),
110)},v=function(a,b,c,e){var f=a.replace(/[\.|;|\|]/g,"_")+".",f=f+(b+"|")+(c+"|");return f=e?f+"0":f+(d.formFocus&&d.getFormFieldName(d.formFocus)===a?"1":"0")},s=function(a,b){for(var c=[],d=0,e=b.length;d<e;d++)if("undefined"!==typeof a[b[d]])if("select-multiple"==a[b[d]][0])for(var f=a[b[d]][1].split("|"),k=0,g=f.length;k<g;k++)c.push(v(b[d],a[b[d]][0],f[k]));else c.push(v(b[d],a[b[d]][0],a[b[d]][1]));return c.join(";")},w=function(a){for(var b in a){var c=b+"";if(1<a[c].length){for(var d=!1,
e=0;e<a[c].length;e++)if("empty"!==a[c][e][1]){a[c]=a[c][e];d=!0;break}if(d)continue}a[c]=a[c][0]}},u=function(){if(!d.formObject)return"";w(d.formFieldData);w(d.formFieldDataUnused);var b=[],c;c=[];if(a.wtTypeof(d.formObject.elements.wt_fields)){var e=d.formObject.elements.wt_fields.value;e&&(c=e.split(";"))}if(0>=c.length)for(var f in d.formFieldData)e=f,"string"===typeof e&&e&&c.push(e);f=!1;if(a.formPathAnalysis){(e=s(d.formFieldDataUnused,c))&&b.push(e);for(var e=0,k=d.formFieldDataPathAnalysis,
g=k.length;e<g;e++){var h;a:{h=0;for(var n=c.length;h<n;h++)if(k[e][0]===c[h]){h=!0;break a}h=!1}h&&(f=!0,b.push(v(k[e][0],k[e][1],k[e][2],!0)))}f&&(c=b[b.length-1],c=c.substr(0,c.length-1),b[b.length-1]=c+"1")}else return s(d.formFieldData,c);return b.join(";")};d.getFormFieldName=function(b){var c=b.name;a.formFieldAttribute&&(c="",(b=a.getAttribute(b,a.formFieldAttribute))||null!==b)&&(c=b);return c};d.getFormFieldValue=function(b){var c=b.type,e="";if("select-multiple"==c){for(var e=[],f=0,k=
b.options,g=k.length;f<g;f++)k[f].selected&&e.push(p(b,k[f]));0>=e.length&&e.push("empty");e=e.join("|")}else"select-one"==c?(e="",-1!==b.selectedIndex&&((e=p(b,b.options[b.selectedIndex]))&&null!==e||(e="empty"))):"checkbox"==c||"radio"==c?(e="",b.checked?(e=p(b))||(e="checked"):e="empty"):"hidden"!=c&&("button"!=c&&"image"!=c&&"reset"!=c&&"submit"!=c)&&(f=(e=p(b))?"filled_out":"empty",q(b)||(f=e),k=d.getFormFieldName(b),"undefined"!==typeof a.formFieldDefaultValue[k]&&a.formFieldDefaultValue[k]==
e&&"empty"!==f&&(f="empty"),f&&null!==f||(f="empty"),e=f);return q(b)&&"select-multiple"!==c&&"empty"!==e&&"filled_out"!==e?"anon":e};d.formTrackInstall=function(a){d.formObject=a?a:document.forms[0]?document.forms[0]:!1;d.formObject&&(d.form="1",g())};d.getFormTrackingData=function(){var b="";if(d.formObject){var c=u();c&&(b+="&fn="+a.wtEscape(d.formName)+"|"+(a.formSubmit?"1":"0"),b+="&ft="+a.wtEscape(c));a.formSubmit=!1;d.formName=!1;d.formObject=!1;d.formFocus=!1;d.formFieldData={};d.formFieldDataUnused=
{};d.formFieldDataPathAnalysis=[]}return b};d.sendFormRequest=function(){"1"!==a.cookie||(a.optOut||a.deactivatePixel)||a.firstParty();!1!==a.beforeUnloadPixel?a.beforeUnloadPixel():a.executePlugin(a.getPluginConfig("form","before"));var b=d.getFormTrackingData();b&&a.quicksend(a.wtEscape(a.contentId.split(";")[0])+",1,"+a.baseparams(),b);!1!==a.afterUnloadPixel?a.afterUnloadPixel():a.executePlugin(a.getPluginConfig("form","after"))};d.init=function(){d.form&&("1"===d.form&&!d.formObject)&&g();return d}}(c);
a.formTrackInstall=a.formTrackObject.formTrackInstall;a.formTrackInit=a.formTrackObject.formTrackInstall;a.sendFormRequest=a.formTrackObject.sendFormRequest;a.checkFormTracking=a.formTrackObject.getFormTrackingData;"complete"===document.readyState?a.formTrackObject.init():a.registerEvent(window,"load",function(){a.formTrackObject.init()})})(f,function(){y("form")});(function(a){a.tabBrowsing="undefined"!==typeof g.tabBrowsing?g.tabBrowsing:"undefined"!==typeof h.tabBrowsing?h.tabBrowsing:!1;var c=
function(){var a="",b="",c=!1,d=!0,e=0,f=null,g=!1,h=function(a){},l=function(){},m=function(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c)},s=function(){var a=1E3;f=window.setInterval(function(){0>=a&&(window.clearInterval(f),g=!1,c||(d=!0,e++,h(e)));a-=5},5)};this.isPageHidden=function(){return c};this.isPageVisible=function(){return d};this.setVisibleCall=function(a){h=a};this.setHiddenCall=function(a){l=a};"undefined"!==typeof document.hidden?(a="hidden",
b="visibilitychange"):"undefined"!==typeof document.mozHidden?(a="mozHidden",b="mozvisibilitychange"):"undefined"!==typeof document.msHidden?(a="msHidden",b="msvisibilitychange"):"undefined"!==typeof document.oHidden?(a="oHidden",b="ovisibilitychange"):"undefined"!==typeof document.webkitHidden&&(a="webkitHidden",b="webkitvisibilitychange");a&&(c=document[a],(d=!c)&&e++,function(){m(document,b,function(){(c=document[a])?(window.clearInterval(f),d=g=!1,l()):g||(g=!0,s())})}())},b=[],e=[],d=null,f=
function(){d=new c;d.setVisibleCall(function(c){if(1<c&&0<e.length){var d=e[0].split("&");c-=1;d[1]="tb="+c+"&cp770="+c+"&"+d[1];a.sendPixel(d.join("&"),e[1])}for(var f=0,g=b.length;f<g;f++)d=b[f][0],c=b[f][1],a.sendPixel(d,c),"wt"===c&&-1===d.search(/&(ct|fn|ft)=.+&/)&&(e=[d,c]);b=[]})};a.tabBrowsing&&f();a.sendTabBrowsingPixel=function(c,f){d.isPageVisible()?(a.sendPixel(c,f),"wt"===f&&-1===c.search(/&(ct|fn|ft)=.+&/)&&(e=[c,f])):b.push([c,f])};a.startTabBrowsing=function(){null===d&&(a.tabBrowsing=
!0,f())}})(f);(function(a){a.globalVisitorIds="undefined"!==typeof g.globalVisitorIds?g.globalVisitorIds:"undefined"!==typeof h.globalVisitorIds?h.globalVisitorIds:!1;a.globalVisitorIds&&(g.execRTA=!0,g.execCDB=!0);(function(a){a.geid=!1;a.execRTA="undefined"!==typeof g.execRTA?g.execRTA:"undefined"!==typeof h.execRTA?h.execRTA:!1;var b=!1,e=function(){b=!0;"string"!==typeof a.execRTA&&(a.execRTA=document.location.protocol+"//cdn.wbtrk.net/js/geid.min.js");var d=a.getCookie("wt_geid");d?"68934a3e9455fa72420237eb"!==
d&&(a.geid=d):a.loadAsynchron(a.execRTA,"wt_geid",function(a,b){a&&wt_geid(b,window)},2E3)};a.execRTA&&e();a.startRTA=function(){b||(a.execRTA=a.execRTA?a.execRTA:!0,e())}})(a);(function(a){a.feid=!1;a.cdbeid=!1;a.execCDB="undefined"!==typeof g.execCDB?g.execCDB:"undefined"!==typeof h.execCDB?h.execCDB:!1;var b=!1,e=function(){b=!0;"string"!==typeof a.execCDB&&(a.execCDB=document.location.protocol+"//cdn.cbtrk.net/js/cdbeid.min.js");var d=a.getCookie("wt_feid"),e=a.getCookie("wt_cdbeid");d&&-1!==
d.search(/^[0-9a-f]{32}$/)&&(a.feid=d);e&&-1!==e.search(/^[0-9a-f]{32}$/)&&(a.cdbeid=e);d&&e||a.loadAsynchron(a.execCDB,"wt_cdbeid",function(a,b){a&&wt_cdbeid(b,window,document,window.navigator)},2E3)};a.execCDB&&e();a.startCDB=function(){b||(a.execCDB=a.execCDB?a.execCDB:!0,e())}})(a)})(f);(function(a){a.cookieManager=function(a,b,e){this.name=a;this.keySeperator="~";this.fieldSeparator="#";this.durationSeperator="|";this.found=!1;this.expires=b?b:!1;this.accessPath=e?e:"/";this.rawValue="";this.fields=
[];this.fieldsDuration=[];var d=function(a){try{return decodeURIComponent(a)}catch(b){return unescape(a)}},f=function(a){try{return encodeURIComponent(a)}catch(b){return escape(a)}};this.read=function(){this.rawValue=null;this.found=!1;for(var a=document.cookie.split(";"),b=0;b<a.length;b++){var c=a[b].substr(0,a[b].indexOf("=")),e=a[b].substr(a[b].indexOf("=")+1),c=c.replace(/^\s+|\s+$/g,"");c==this.name&&(this.rawValue=e,this.found=!0)}if(null!==this.rawValue){a=b=0;do a=this.rawValue.indexOf(this.fieldSeparator,
b),-1!=a&&(b=this.rawValue.substring(b,a).split(this.durationSeperator),c=b[0].split(this.keySeperator),this.fields[c[0]]=d(c[1]),this.fieldsDuration[c[0]]=parseInt(d(b[1])),b=a+1);while(-1!==a&&a!==this.rawValue.length-1)}return this.found};this.getSize=function(){var a=(new Date).getTime(),b="",c;for(c in this.fields){var d=c+"";this.fieldsDuration[d]>=a&&(b+=f(d)+this.keySeperator+f(this.fields[d])+this.durationSeperator+f(this.fieldsDuration[d])+this.fieldSeparator)}return b.length};this.write=
function(){var a=(new Date).getTime(),b=!0,c=this.name+"=",d;for(d in this.fields){var e=d+"";this.fieldsDuration[e]>=a&&(c+=f(e)+this.keySeperator+f(this.fields[e])+this.durationSeperator+f(this.fieldsDuration[e])+this.fieldSeparator,b=!1)}a=b?-99999:this.expires;""!==a&&"number"===typeof a&&(b=new Date,b.setTime((new Date).getTime()+864E5*a),c+="; expires="+b.toGMTString());null!==this.accessPath&&(c+="; PATH="+this.accessPath);a=location.hostname;-1==a.search(/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$/)&&
(a=location.hostname.split("."),a=a[a.length-2]+"."+a[a.length-1]);document.cookie=c+("; DOMAIN="+a)};this.remove=function(){this.expires=-10;this.write();return this.read()};this.get=function(a){var b=(new Date).getTime();return this.fieldsDuration[a]>=b?this.fields[a]:""};this.set=function(a,b,c,d,e){c||(c=31536E3);d||(d="last");var f=(new Date).getTime();if("first"==d&&""!==this.fields[a]&&null!==this.fields[a]&&this.fieldsDuration[a]>=f)return this.fields[a];this.fields[a]=b;this.fieldsDuration[a]=
f+1E3*parseInt(c);e||this.write();return b};this.prepare=function(a,b,c,d){return this.set(a,b,c,d,!0)};this.read()}})(f)};
if("object"===typeof webtrekkConfig&&"object"===typeof webtrekkConfig.safetag&&-1===document.cookie.indexOf("wt_r=1")){var wts=wts||[],wt_safetagConfig={async:"undefined"!==typeof webtrekkConfig.safetag.async?webtrekkConfig.safetag.async:!0,timeout:"undefined"!==typeof webtrekkConfig.safetag.timeout?webtrekkConfig.safetag.timeout:2E3,safetagDomain:"undefined"!==typeof webtrekkConfig.safetag.safetagDomain?webtrekkConfig.safetag.safetagDomain:!1,safetagId:"undefined"!==typeof webtrekkConfig.safetag.safetagId?
webtrekkConfig.safetag.safetagId:!1,customDomain:"undefined"!==typeof webtrekkConfig.safetag.customDomain?webtrekkConfig.safetag.customDomain:!1,customPath:"undefined"!==typeof webtrekkConfig.safetag.customPath?webtrekkConfig.safetag.customPath:!1,option:"undefined"!==typeof webtrekkConfig.safetag.option?webtrekkConfig.safetag.option:{}};(function(g,y){var s=function(f){try{return encodeURIComponent(f)}catch(g){return escape(f)}},u=document.location.protocol;if("http:"==u||"https:"==u){var m="";g.customDomain&&
g.customPath?m=u+"//"+g.customDomain+"/"+g.customPath:g.safetagDomain&&(g.safetagId&&-1!==g.safetagId.search(/^\d+$/))&&(m=u+"//"+g.safetagDomain+"/resp/api/get/"+g.safetagId+"?url="+s(document.location.href));if(m){for(var x in g.option)m+="&"+x+"="+s(g.option[x]);webtrekkV3.prototype.safetag=g;webtrekkV3.prototype.safetagInProgress=!0;webtrekkV3.prototype.safetagParameter={};webtrekkV3.prototype.update=function(){};window.wts=y;window.safetagLoaderHandler=function(f,g){if(f&&g)if("onerror"==g)webtrekkV3.prototype.safetagInProgress=
!1;else if("onload"==g){if("undefined"!==typeof wt_r&&!isNaN(wt_r)){var m=new Date;document.cookie="wt_r=1;path=/;expires="+m.toUTCString(m.setTime(m.getTime()+1E3*parseInt(wt_r)))}webtrekkV3.prototype.safetagInProgress=!1}else"onreadystatechange"!=g||"loaded"!=f.readyState&&"complete"!=f.readyState||(f.onreadystatechange=null,f.onload(h))};if(g.async||"complete"===document.readyState||"interactive"===document.readyState){var s=document.getElementsByTagName("script")[0],h=document.createElement("script");
h.async=g.async;h.type="text/javascript";h.onerror=function(){safetagLoaderHandler(h,"onerror")};h.onload=function(){safetagLoaderHandler(h,"onload")};h.onreadystatechange=function(){safetagLoaderHandler(h,"onreadystatechange")};h.src=m;s.parentNode.insertBefore(h,s)}else m='<script type="text/javascript" src="'+m+'" onerror="safetagLoaderHandler(this,\'onerror\')"',m+=" onload=\"safetagLoaderHandler(this,'onload')\"",m+=" onreadystatechange=\"safetagLoaderHandler(this,'onreadystatechange')\"",m+=
">\x3c/script>",document.write(m)}}})(wt_safetagConfig,wts)};
/** End webtrekk_v4.js */